### ISSUE TITLE
Publish sources for music

### ISSUE THREAD

**Issue by Zverik** [sky-music/sky-music.github.io#15]
Please public source files for songs. If done, this would allow updating sheets when the python script changes, and also we could improve sheets a bit, e.g. split into parts for easier learning.

**Comment by jmmelko** [comment]
The source file of each song is actually “hidden” inside the HTML file.

* You can retrieve the notes by opening the notes inside a text editor, and looking for the 'ascii' tag
* Or you can feed the HTML file back directly to the Visual Sheet maker. It should be able to read the notes in the ascii tag and regenerate the song in other formats. This way it will export the song notes into TXT files.

**Comment by jmmelko** [comment]
Updated docs

**Comment by Zverik** [comment]
Thanks, I have found some of the sources! Alas, not all: seems like songs uploaded in May 2021  are built with a different script. [For example, this one](https://github.com/sky-music/sky-music.github.io/blob/master/songs/movies/Aladdin_-_A_Whole_New_World_(Alan_Menken).html).

**Comment by jmmelko** [comment]
Yes.
For these old songs, you’ll have to do the following, in order:
* click on the “export as JSON” button in the top right hand corner
* feed the JSON.txt to the Visual Sheet Maker at <https://jmmelko.eu.pythonanywhere.com> (no account required)
* check the TXT and JSON output formats when asked for
* try to feed the newly generates JSON to Specy’s player and composer at <https://specy.github.io/skyMusic>. If it fails, report to me.
* otherwise, use the notes in the xxxx_sky.txt text file

I will try to update the docs

**Comment by Zverik** [comment]
Ah, I have missed the exporting button, thanks!

**Comment by jmmelko** [comment]
Yes but beware: I have been told the exported JSON can no longer be read by Specy’s website, so you might have to go through all the steps listed above
